name: 'Si√¢n Roberts, M.Sc. Registered Psychologist'
favicon: null
layout_spectrum: 0.533121608896181
typography_spectrum: 0.70845
title: Edmonton Psychologist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
